export default class Statics {
static mysteryList = [
    {
        part: "radosne",
        nr: "1",
        mystery: "Zwiastowanie Najświętszej Maryi Pannie",
        meditation1: "Maryjo, miałaś tyle spraw na głowie, tak ważne wydarzenia. Przecież byłaś zakochana. Czekały cię zaślubiny z Józefem całkowita zmiana życia. I w tym całym przejęciu byłaś tak otwarta, że usłyszałaś zapraszające słowa Boga? Jak to zrobiłaś, nam tak trudno spotkać się z Bogiem, gdy jesteśmy przejęte czymś ważnym, co angażuje nasze uczucia, serce, wszystko. Wtedy, to robi się tak ważne, że chorujemy na głuchotę serca.\r\nMatko Droga, pomóż usłyszeć szept Boga, gdy cały świat krzyczy nam do ucha.",
        meditation2: "„Niech bystrość naszych oczu – mówi św. Piotr Chryzolog - będzie czysta, abyśmy mogli spojrzeć na jasność boskiego wschodu! Bo jeśli zdrowe i czyste oko z trudnością znosi promienie wschodzącego słońca, to ileż więcej potrzeba duchowej siły widzenia, aby znieść blask przychodzącego i rzucającego promienie Stwórcy!”\r\n„W szóstym miesiącu posłał Bóg anioła Gabriela do miasta w Galilei, zwanego Nazaret, do Dziewicy poślubionej mężowi imieniem Józef, a Dziewicy było na imię Maryja” (Łk 1, 26-27). Ewangelista przedstawia miejsce, czas, osobę, aby opowiadanie umocnić wyraźnymi okolicznościami wydarzeń. Do Dziewicy posyła uskrzydlonego posłańca, aby wręczył skarb, przyjął posag, zaniósł łaskę. Szybko leci pośrednik, aby wybraną przez Boga Oblubienicę odwieść od ziemskiego wesela, nie żeby odebrać Józefowi Małżonkę, lecz by Ją oddać Chrystusowi”\r\nAnioł wręczył Maryi skarb – Jezusa, odebrał i przekazał Bogu Fiat Maryi, a z Nieba zabrał i zaniósł dla Dziewicy łaskę. Czy takie rozmowy i dialogi toczą się w naszym życiu? Przecież i nasze  życie to nie tylko oderwanie od ziemskiego wesela, ale i radość bycia Jezusową.",
        meditation3: "Chryste, w dniu Zwiastowania Ojciec Twój posłał do Nazaretu Zwiastuna, aby wybranej dla Ciebie Matce opowiedzieć o tym, że w Niej Twoje Słowo ma okryć się Ciałem. I odtąd, od Zwiastowania, jest na świecie Boże – Ciało. Przez wiarę oglądamy Twoje Boże Ciało w Eucharystii. I wielbimy Ciebie przenosząc się myślą do Nazaretu, gdzie Twoja Matka słyszy wolę Ojca: Oto poczniesz i porodzisz Syna.\r\n\r\n \r\n\r\nWe mnie również Bóg złożył ładunek życia. Historia chleba zaczyna się od ziarnka, podobnie jak powołanie człowieka do życia by stać się chlebem. Dlatego ziarno musi oddać się Bogu: „losy moje w rękach Twoich”, więc idę w życie by wydać owoc. Ta tajemnica dokonuje się również w Twoim sercu. Może właśnie teraz jest czas by prosić o serce zdolne być chlebem."
    },
    {
        part: "radosne",
        nr: "2",
        mystery: "Nawiedzenie Świętej Elżbiety",
        meditation1: "Ruszyłaś Maryjo z pośpiechem w góry do Elżbiety, nie po to by użalić się jak bardzo czujesz się niegodna propozycji Boga, lecz by służyć drugiemu człowiekowi z wdzięcznością, za wielkie rzeczy, które uczynił Ci Wszechmocny.\r\nNaucz mnie Matko, jak dzielić się Jezusem w moim życiu, choćby najmniejszym.",
        meditation2: "Maryja spieszy do Elżbiety, i tam w radości serca wyznaje: ”Wielbi dusza moja Pana”. Spotkanie z Bogiem sprawia, że serce zaczyna uwielbiać. To modlitwa w której wyznaje się, że Bóg jest Bogiem. Wysławia Go dla Niego samego, oddaje cześć Jego Obecności.\r\nŚw. Beda tak komentuje kantyk Maryi: „Ona w Jezusie mogła bardziej weselić się od innych świętych. Ten, którego znała jako wiecznego Sprawcę zbawienia, z Jej ciała w czasie się narodzi. Niczego nie przypisuje własnym zasługom Ta, która całą swą wielkość odnosi do Jego daru. On z natury swej potężny i wielki, czyni zawsze wiernych z małych, a słabych mocnymi. Dlatego dodała: „Święte jest imię Jego”, aby zachęcić do wzywania Jego imienia. To jest właśnie imię, o którym powiedziała wyżej „Rozradował się duch mój w Bogu, Zbawicielu moim”\r\n„Przemawiajcie do siebie wzajemnie w psalmach i hymnach, i pieśniach pełnych ducha, śpiewając i wysławiając Pana w waszych sercach” (Ef 5, 19). Prośmy Maryję, abyśmy odnowieni w Duchu, układały również pieśni i hymny naszego  życia tak, by były świadectwem radości i uwielbienia Boga za to, że jest naszym Bogiem",
        meditation3: "Twoja Matka przyniosła Ciebie, Jezu Chryste, do Elżbiety. Była to pierwsza procesja Bożego Ciała na świecie, a prawdziwą żywą monstrancją była Maryja. Odtąd my, Chryste, nosimy Twoje Ciało po ziemi. Radujemy się tym, że pozwalasz się nosić. Na naszym stole spotkały się chleb i kwiaty. Pokrojony bochenek odsłania tajemnice chleba. W każdej kromce jest wiele cudownych zjawisk. Są powiązane pomiędzy tym co boskie, ziemskie i ludzkie. Przy chlebie skupiają się ręce, którym Bóg kazał dzielić chleb i błogosławić go.\r\n\r\n \r\n\r\nMaryja swojej radości nie zatrzymuje dla siebie, a zatem dzielenie się to nie tyle radowanie się z posiadania Jezusa, ale poniesienie Go innym, ofiarowanie Go jak kromki chleba, by i oni potrafili się dzielić."
    },
    {
        part: "radosne",
        nr: "3",
        mystery: "Narodzenie Pana Jezusa",
        meditation1: "Jezus chce narodzić się w każdym ludzkim sercu, lecz nikogo nie zmusza by otwarł Mu drzwi. Nawet Maryja przyjęła zamknięte drzwi gospody. Odeszli, by szukać dalej. Jezus daje wolność. Od każdej z nas zależy czy Jezus się narodzi, on czeka za drzwiami, i nie martw się, że twoje serca jest jak zwykła śmierdząca stajnia, On nią nie gardzi. On chce się tak z Tobą spotkać.",
        meditation2: "„Oto mówi Ewangelia – pisze Anonim z IX w- że gdy Maryja porodziła, złożyła Syna owiniętego w pieluszki w żłobie. I słusznie, że rodzi w drodze, bo przyszedł, aby nam pokazać drogę; Ten, który przyszedł, aby nam pokazać przestronność Królestwa, chciał narodzić się w ciasnym żłobie. Ten, który przyszedł, aby nam dać szatę nieśmiertelności, chciał, by go owinięto nie jedwabnymi, ani złotymi, haftowanymi pieluszkami, ale najbiedniejszymi.\r\nCo na to mamy powiedzieć, bracie i siostro? Należy zawołać z psalmistą „Cóż oddam Panu za wszystko, co mi uczynił?” (Ps 115). Dajmy to, co możemy: jałmużnę, czuwanie, łzy, pokój, przebaczenie”",
        meditation3: "To było w Betlejem… żłób był pusty – jak niekiedy bywa pusta świątynia, ołtarz, kielich… ale, gdy Matka Boga wydała Ciebie na świat, żłób stał się pełny Boga – jak pełne są nasze świątynie, ołtarze, kielichy. Twoje Boże Narodzenie było narodzeniem się chleba żywego, który z nieba zstąpił i zapowiedzą życia: „Kto spożywa Ciało moje, żyć będzie na wieki”.\r\n\r\n \r\n\r\nNasza praca i sianie, Twoje Boże planowanie. Wyszedł gospodarz na rolę i zadumał się. Z ziarnem jest tak samo jak z człowiekiem, rośnie sam nie wiesz jak – nie podpatrzysz tego. Ziemia daje nowe życie, w nie j ziarno pęka, zrzuca to co przyniosło ze świata, a co Ewangelia nazywa „starym”. Bóg dopuszcza upokorzenie w naszym życiu, aby doprowadzić nas do pokory serca. On oczyszcza i uszlachetnia naszą wiarę po to abyśmy całą ufność złożyli w Nim."
    },
    {
        part: "radosne",
        nr: "4",
        mystery: "Ofiarowanie Jezusa w świątyni",
        meditation1: "Dopiero co się narodził a ty matko oddajesz Go całego Bogu. Ofiarować się na przepadłe Jezusowi, nie pozostawiając nic dla siebie. To boli. Ale w tym bólu rodzi się radość. Odzyskujemy wolność. To co oddam Bogu na serio to tak na prawdę staję się moje.\r\nMaryjo pomóż mi zrozumieć, iż oddając siebie- posiadam siebie.",
        meditation2: "Maryja wprowadza nas do świątyni, gdzie wchodzi z Jezusem na rękach i składa skromny dar: dwa młode gołębie.\r\nZłóżmy razem z Nią ofiarę naszych serc. „Składajmy śluby – wołają Ojcowie Kościoła - Bóg da łaskę ich spełnienia. Byłoby rzeczą przykra bracia, gdyby znalazł się ktoś, kto Bogu nie złoży dziś ofiary. Gdy przyjmujemy bowiem królów lub przyjaciół, to dajemy im dary, a czyż nie damy Panu, Stwórcy wszystkiego, który właśnie dziś do nas przychodzi? Niczego bardziej od nas nie wymaga, tylko ofiary samych siebie”\r\nWszystko, cokolwiek mamy i posiadamy, pochodzi od Boga. Żyć tylko dla siebie, a Boga pozostawiać za bramą naszego życia, to największa strata. Nasza radość ukryta jest w drodze Maryi do świątyni, by tam oddać Bogu, to co najcenniejsze. Ile razy, droga Siostro i bracie, przebyłeś już tę droge?",
        meditation3: "Dokąd zaniosła Cię Twoja Matka, aby ofiarować Ojcu Przedwiecznemu? Do świątyni. Tę drogę ustaliła sama Maryja. Ona, Matka Wieczystego Kapłana, wiedziała najlepiej, gdzie ma się dopełnić Twoje nieustanne oddanie Ojcu. Zanim sam ofiarowałeś się Ojcu na krzyżu Twoja matka ofiarowała Cię w świątyni.\r\n\r\n \r\n\r\nNikt nie podpatrzył kiedy ziemia się otwarła ukazując biały kiełek, przejrzysty czysty na butwiejących szczątkach zrzuconej powłoki. Bóg sam, który okrywa doliny zbożami dał mu szatę świetlistej trawy, potem źdźbło a na koniec kłos. Całe bogactwo i wartość wewnętrzna jest w ziarnie. Tylko ziarno przemienia Bóg w Ciało. Po ludzku rzecz oceniając, trzeba dużo mieć, aby coś dawać. Inaczej jest w porządku Bożym. Tu trzeba być ubogim, aby wiele otrzymać, a otrzymawszy, znowu ofiarować wszystko Bogu, by jeszcze więcej otrzymać."
    },
    {
        part: "radosne",
        nr: "5",
        mystery: "Odnalezienie Jezusa w świątyni",
        meditation1: "Szukam Jezu Ciebie, to Ciebie pragnie moja dusza. Ale jakiego ja szukam Jezusa? Co przytuli, pogłaszcze nie będzie wymagał ofiary? Bo gdy tylko na horyzoncie Jezus daje mi się znaleźć jako ukrzyżowany, to raczej skręcam w następną ścieżkę, udaje, że nie widzę. Nie chce widzieć! \r\nMaryjo szukająca, pomóż mi odnaleźć w życiu prawdziwe oblicze Jezusa, który kocha, aż po krzyż.",
        meditation2: "Czytamy w Ewangelii: „Gdy miał lat dwanaście”. Św. Ambroży rozważając tę tajemnicę zaznacza, że „Jezus nie napróżno zapomniał o swych rodzicach według ciała. Rodzice znaleźli Go trzeciego dnia w świątyni, co było znakiem Jego ukazania się na trzeci dzień po jego zwycięskiej męce. Wówczas, On, uznany za zgubionego i zmarłego, objawił się naszej wierze jako uwielbiony na stolicy niebieskiej. Potem wrócił do Nazaretu i „był im poddany” (Łk 2, 51). Owo poddanie nie jest oznaka słabości, ale jest oznaką czci oddawanej Ojcu.”\r\nCzy jesteśmy w tym, co należy do naszego Ojca. Jezus wskazuje nam drogę. Błogosławić Boga za wszelkie Jego dzieła, za nasze zagubienia i odnalezienia, za to, co jest naszym bogactwem, ale także za skarb naszego ubóstwa. Błogosławić za czas spędzony w świątyni i powroty do Nazaretu.",
        meditation3: "Znaleziono Ciebie, Jezu Chryste w świątyni. Dziwiła się temu Twoja Matka, chociaż sama Cię kiedyś tam przyniosła. I dziwił się Józef. Dałeś nam wskazania, że najwspanialszym miejscem, w którym zawsze Ciebie można znaleźć, jest Świątynia. Żniwiarz pochyla się z ręką na sierpie. Ponosi wysoko pierwszy snop… Znikły kłosy w dłoniach żniwiarza, potem roztarł młyński kamień. Stał się chleb, chleb – pokarm dla innych.\r\n\r\n \r\n\r\nPanie i mnie uczyń darem dla innych. Domem chleba być chcemy – prawdziwym Nazaret dziś, jutro, pojutrze. A najdroższa nasza matka niechaj ma wejście w ten dom i klucze… dla wszystkich ma starczyć chleba. Tak, jak Maryi niekiedy Jezus jakby się ukrywał przed nami, po to byśmy Go wytrwale szukali, byśmy bardziej za nim tęsknili, bardziej go pragnęli. Im bardziej szukamy Jezusa, tym bardziej pozwalamy się mu odnaleźć i obdarować Jego miłością innych."
    },
    {
        part: "chwalebne",
        nr: "1",
        mystery: "Zmartwychwstanie Pana Jezusa",
        meditation1: "Ty jesteś Panie Jezu Zmartwychwstaniem i życiem! Nie pozwalasz, abyśmy trwali w śmierci, ale wzywasz nas do pełni życia z Tobą.\r\nPrzynosimy dziś kwiat symbolizujący Europę. Prosimy, aby na starym kontynencie na nowo rozkwitła wiara. Daj Panie nowe życie i nowego Ducha wszystkim europejczykom, spraw by odrzucili chwilowe przyjemności i na nowo wybrali Ciebie, Dawce Życia wiecznego!",
        meditation2: "Z „Dzienniczka”:\r\nDziękuję Ci, o Panie, Mistrzu mój,\r\nżeś mnie całą przemienił w Siebie.\r\nIdziesz ze mną przez życia trud i znój.\r\nNie lękam się niczego, gdy mam w sercu Ciebie.\r\n(Dz. 1001)\r\n\r\n\r\n\r\nŚw. Faustyna potrafiła żyć tajemnicą Zmartwychwstania Pańskiego.\r\nOna, powtarzając za Marią Magdaleną z podziwem pozdrawiała swojego Pana: „Mistrzu”, „Rabbuni” (J 20,16). Ona nie lękała się na próżno, gdyż pamiętała polecenie zmartwychwstałego Jezusa wobec Swoich uczniów: „Pokój Wam” ( J 20, 19).\r\nOna dziękowała za przemianę swojego serca, za nowe życie, które On sam daje. Skąd brała siły? Z wpatrywania się w oblicze miłosiernego Jezusa, w Jego oczy, w Jego serce, z którego wypływają dwa strumienie, z powtarzania z głębokości duszy: „Jezu, ufam Tobie!”",
        meditation3: "Ileż wzruszających dowodów delikatnej miłości ku nam, słabym i grzesznym, okazał Jezus po swoim zmartwychwstaniu, objawiając się i tak łaskawie obcując ze swoimi uczniami. Jezus i nam służy nadal swoją miłością przez sakramentalną obecność w Eucharystii."
    },
    {
        part: "chwalebne",
        nr: "2",
        mystery: "Wniebowstąpienie Pana Jezusa",
        meditation1: "Poszedłeś Panie do Ojca przygotować nam miejsce, abyśmy pamiętali, że tu na ziemi jesteśmy tylko przechodniami. Nasz prawdziwy dom jest w Niebie i do Niego podążamy. Pomóż nam Panie wznosić nasze serca i oczy ku temu co od Ojca pochodzi.\r\nPrzynosimy dziś pustą miskę symbolizującą Afrykę. Prosimy Cię Panie, abyś wypełnił pragnienia mieszkańców tego kontynentu. Obdarz kraje Afryki upragnionym pokojem. Daj pożywienie i schronienie wszystkim potrzebującym i spraw, aby wszyscy ludzie na tej ziemi mogli Cię poznać i w Tobie odnaleźć swój dom, pokój i szczęście.",
        meditation2: "Jezu, Hostio, którego w tej chwili przyjęłam do serca swego, a w tym zjednoczeniu z Tobą ofiaruję się Ojcu Niebieskiemu (...).\r\n(Dz. 1264)\r\n\r\nNiebo, to stan absolutnego szczęścia, stan całkowitego zjednoczenia się z Bogiem. Stan, którego św. Faustyna doświadczyła już tutaj na ziemi, oddając siebie całkowicie w ręce swojego Oblubieńca, w którym odnalazła całe swoje szczęście. Czy możemy dążyć do takiej relacji z Panem? Tak, możemy! Spotykając Go w Eucharystii, w miłosiernej ofierze naszego Pana, w której On się nam cały daje, abyśmy już tutaj na ziemi odkryły przedsmak nieba.",
        meditation3: "Jezus Chrystus wskazał nam swym życiem i nauką drogę do nieba a przez swą mękę i śmierć na krzyżu przywrócił prawo do niego. Jezus chce  byśmy szli za Jego przykładem w służbie Bogu i ludziom. A wówczas na pewno ujrzymy Go kiedyś w otoczeniu niezliczonych dusz zbawionych."
    },
    {
        part: "chwalebne",
        nr: "3",
        mystery: "Zesłanie Ducha Świętego",
        meditation1: "Nie chcesz Panie, abyśmy na ziemi byli sierotami. Zawsze dajesz nam Twojego Ducha – Ducha Świętego, który nas poucza i do Ciebie prowadzi.\r\nPrzynosimy przed Twój ołtarz kolorowe pióra. Symbolizują one różnorodność mieszkańców obu Ameryk. Spraw Panie, aby amerykanie potrafili otwierać się na siebie. Niech Twój Święty Duch uczyni ich serca wolnymi, gotowymi przejść ponad podziałami.",
        meditation2: "O Jezu mój, (...) pragnę spełnić wolę Twoją świętą; pragnę nawrócenia dusz; pragnę, aby uwielbione było miłosierdzie Twoje; (...) aby Święto Miłosierdzia było czczone na całym świecie;\r\n(Dz. 1581)\r\n\r\nPragnienia- one popychają nas do działania. One wypływają z głębokości serca. One są darem samego Boga, budzą się w nas za pomocą Ducha Świętego. Są nam dane, aby realizować wezwania, do których Bóg nas zaprasza. Św. Faustyna też miała swoją misję i cała poświęciła się temu, aby głosić światu Boże Miłosierdzie. Pragnęła pełnić wolę tego, którego tak bardzo umiłowała. I w pewnym momencie pragnienie Jezusa stało się jej osobistym pragnieniem, które wypełniała hojnie i w wolności, umocniona darami Ducha Świętego.",
        meditation3: "Jezus Chrystu, Pan i Mistrz nasz, przyszedł, aby nam służyć – to i my odkupione przez niego dzieci Boże, mamy podobnie służyć naszym bliźnim, aby nasze zjednoczenie z Bogiem przez miłość wyrażało się w służbie rodzinie ludzkiej. A tego wszystkiego uczy nas Duch Święty."
    },
    {
        part: "chwalebne",
        nr: "4",
        mystery: "Wniebowzięcie Najświętszej Maryi Panny",
        meditation1: "Panie Jezu, Ty za piękne życie wziąłeś Maryję z ciałem i duszą do nieba. Pomóż i nam dbać o czystość naszych serc i zawsze za przykładem Matki Bożej mówić Tobie „tak”.\r\nPrzynosimy Ci Panie Jezu ziarno, jest ono symbolem krajów Azji, gdzie Twoje Słowo znalazło żyzną ziemię do wzrostu. Prosimy Cię, aby na tym kontynencie wiara mogła być wyznawana i głoszona przez wszystkich i dla wszystkich spragnionych Bożego Słowa.",
        meditation2: "„O Matko, Dziewico Niepokalana,\r\nw Tobie odbija mi się promień Boga.\r\nTy mnie uczysz, jak wśród burz kochać Pana,\r\nTyś mi tarczą i obroną od wroga.”\r\n(Dz. 1232)\r\n\r\nTe słowa św. Faustyny są pięknym świadectwem miłości do Matki Bożej. Ona oddała się całkowicie w opiekę Tej, przez którą jej Oblubieniec przyszedł na świat. Tej, którą nazywamy Matką Miłosierdzia, bo towarzysząc wiernie Jezusowi, sama towarzyszyła w tajemnicy Miłosierdzia Bożego. Maryja zawsze prowadza nas do swojego Syna, sama będąc w niebie zjednoczona z Bogiem, prowadza nas w ramiona miłosiernego Ojca, aby odnaleźć w nich nasze prawdziwe przeznaczenie i nasze zbawienie. Uświadamiając sobie tę prawdę, rozumiemy pragnienie s. Faustyny, by często oddawać się w ręce najlepszej Matce.",
        meditation3: "Wewnętrzną odpowiedzią Maryi na powołanie Jej na Matkę Syna Człowieczego było: „Oto Ja Służebnica Pańska”. Słowa te spełniała przez całe życie. Z woli Bożej służyła jako Matka Jezusowi i z woli Bożej służy także nam jako Matka. Została Ona z duszą i ciałem wzięta do nieba, ale służy nam nadal troszcząc się i zabiegając, byśmy też mogli być kiedyś razem z Jezusem i z Nią w niebie."
    },
    {
        part: "chwalebne",
        nr: "5",
        mystery: "koronowanie Maryi na Królową Nieba i Ziemi",
        meditation1: "Maryja jest Królową, ale jej królowanie to nie władza i zaszczyty, ale służba i wypełnianie woli Bożej. Prosimy Cię Panie, abyśmy za przykładem Maryi potrafili oddawać swoje życie naszym braciom i siostrom.\r\nPrzynosimy dziś świecę, symbolizującą Australię i Oceanię. Prosimy Panie, abyś rozjaśnił swoim światłem serca zamieszkujących tam ludzi, aby mogli oni poznawać Ciebie i Twoją naukę.",
        meditation2: "„Widzenie Matki Bożej. W jasności wielkiej ujrzałam Matką Bożą w białej sukni, (...). Płaszcz miała szafirowy (...), włosy rozpuszczone, ślicznie ułożone i korona ze złota, która miała w zakończeniach krzyżyki.”\r\n(Dz. 1585)\r\n\r\nKorona i krzyż to droga Maryi - droga królewska, którą przyjęła od Boga Przedwiecznego. Jest Królową, która przyjęła wszystko do czego była zapraszana. Niczego Bogu nie odmówiła. Kiedy Jezus jest naszym jedynym królem, przyjmujemy krzyż tak jak On i jak Jego Matka. Krzyż staje się wtedy naszą koroną, naszą chlubą. Ta droga uczyniła Ją królową nieba i ziemi. Św. Faustyna także nie bała się tej korony. Nosiła koronę cierpień fizycznych i duchowych z odwagą i zgodą, bo robiła to z miłości do swojego Oblubieńca i dla zbawienia dusz, doświadczała, że w tym jest nadzieja i tajemnica Bożego Miłosierdzia.",
        meditation3: "Pan Bóg nie powtarza się w świętych swoich. Stać Go na nieskończoną rozmaitość swoich sług. Życie na ziemi jest tylko zapoczątkowaniem pełnej aktywności duchowej jaka się okaże w niebie. Najświętsza Maryja Panna wywyższona ponad wszystkie stworzenia i najbliższa tronu Bożego, dopomaga nam do osiągnięcia w niebie w pełni naszego osobistego powołania."
    },
    {
        part: "swiatla",
        nr: "1",
        mystery: "Chrzest Pana Jezusa w Jordanie",
        meditation1: "„A gdy Jezus został ochrzczony, natychmiast wyszedł z wody. A oto otworzyły Mu się niebiosa”. (Mt 3, 16) Dlaczego otworzyły się niebiosa? – pyta św. Jan Chryzostom i odpowiada - Abyś poznał, że dzieje się to także wtedy, kiedy ty przyjmujesz chrzest. Bóg wzywa cię do ojczyzny niebieskiej, pokazuje, że nic wspólnego nie masz z ziemią. Jeśli nawet tego nie widzisz, uwierz w to. Także gołębica dlatego wtedy się ukazała, aby – jakby palcem – wskazać wszystkim obecnym Syna Bożego. Ale nie tylko dlatego, ale także abyś poznał, na ciebie zstępuje Duch, kiedy przyjmujesz chrzest”\r\n\r\n \r\n\r\nProsimy Cię Panie o wierność. Daj nam światłe oczy serca, aby wśród nas widzialne były Twoje otwarte niebiosa. Prosimy Cię o wierność łasce chrztu, aby to wszystko co przesłania nam Twoje otwarte niebiosa zostało oświetlone łaska Twego Ducha. Niech wierność w oddaniu się Tobie pomaga dostrzegać w naszych bliźnich Twoich umiłowanych synów i córki.",
        meditation2: "O szarym świcie, z szarych domów wychodzą ludzie, śpieszą do szarej pracy. Jak łatwo zapominają że noszą w sobie światło, że zrodzeni są ze światła. Boże  rozedrzyj nade mną szare niebo, niech pierzchną chmury cięższe od wieczornych myśli. Wiem, że za nimi, że tam we mnie jaśnieje błękitna kropla łaski – jaśniejsza od oczu matki w dzień mojego chrztu. Daj Boże, bym umiał wydobyć ją z zakurzonego wnętrza mojego serca by świeciła w ciemnościach.\r\n\r\nJezu oddajemy Tobie ludzi młodych, spragnionych miłości, niech Twoje światło rozjaśni wszystkie zakamarki serc i niech przekonuje o Twojej darmowej miłości",
        meditation3: "„O mój Jezu”\r\n\r\n\r\nNad Jordanem dał się słyszeć głos: „ To jest mój Syn Umiłowany.” Objawienie Syna Bożego, naszego Pana Jezusa Chrystusa. Jest to dla nas moment, żeby się zatrzymać, zreflektować. Kto jest moim Panem? Niech jest to nasza szczera odpowiedź. Kto tak naprawdę jest moim Panem, od którego zależą moje codzienne wybory, decyzje?\r\n„O mój Jezu„ bądź moim jedynym Panem."
    },
    {
        part: "swiatla",
        nr: "2",
        mystery: "Wesele w Kanie",
        meditation1: "„Podziwiajmy cud, który uczynił Jezus ze względu na nasze odnowienie. Nie bez powodu przyszedł na wesele – pisze św. Augustyn - Nawet bez cudu w tym wydarzeniu coś z tajemnicy staje przed nami otworem. Pukajmy, aby nam otworzono i abyśmy zostali upojeni niewidzialnym winem: byliśmy wodą, a On uczynił nas winem, dał nam wiedzę, znamy bowiem wiarę w Tego, którego wcześniej nie znaliśmy.”\r\n\r\n \r\n\r\nProsimy Cię Panie o posłuszeństwo. Spojrzyj łaskawie na nasze stągwie życia i przemień je. Naucz przyjmować z uległością zaproszenie Maryi: „Zróbcie wszystko cokolwiek wam powie”, abyśmy nie uronili ani jednego Bożego Słowa, abyśmy nie zlekceważyli Bożej Woli wobec nas. Prosimy Cię Panie o posłuszne serca, bo tylko wtedy zdarzy się cud i dostąpimy łaski oglądania Ciebie pośród nas.",
        meditation2: "Kiedyś było i nasze wesele i nasza Kana i uroczyste przyjęcie Jezusa do serca, a potem życie w ciągłym biegu. O Bogu zaproszonym kiedyś na ucztę życia przypomną sobie być może gdy zabraknie wina zdrowia, czasu lub miłości. Boże mozolnie i z trudem buduję moje życie. Daj odwagę bym zburzył, co nie na Tobie zbudowane. Bym szukał Twojego Oblicza nie tylko w potrzebie. I daj szczerość serca kiedy mówię: ”Bądź wola Twoja”.\r\n\r\nJezu przed Twoje oblicze przynosimy serca młodych ludzi, którzy są zagubieni pośród różnych dróg jakie są im proponowane. Niech Twoje Boże światło dotknie ich serc i uzdolni do odważnej odpowiedzi na Twe wezwanie.",
        meditation3: "„Przebacz nam nasze grzechy”\r\n\r\n\r\nJezu stajemy przed Tobą tacy, jacy jesteśmy. Jak często brak nam wiary, że przy Tobie niczego nam nie braknie. Woda, którą mieliśmy zaczerpnąć na Twoje słowa, zostanie przemieniona w wino. Czy wierzę, że moje codzienne, drobne czyny mają wartość, a ich wartością jest miłość. Czy jednak zaczerpnę tej wody i pozwolę, abyś Ty ją przemienił?"
    },
    {
        part: "swiatla",
        nr: "3",
        mystery: "Głoszenie Ewangelii",
        meditation1: "„To mamy wiedzieć o królestwie Bożym – zachęcają Ojcowie Kościoła - że nic nie ma wspólnego sprawiedliwość z niesprawiedliwością ani światło z ciemnością, ani królestwo Boże nie może współistnieć z królestwem grzechu. Jeżeli więc chcemy, aby Bóg w nas panował, w żaden sposób „nie może królować grzech w naszym śmiertelnym ciele”, lecz mamy zadawać śmierć temu, co w nas jest ziemskie, a przynosić owoce Ducha. I mamy być dla Boga tym duchowym rajem, który On nawiedza i w którym On tylko panuje wraz z Chrystusem. Niech będzie w nas Pan, aż rzuci pod swoje stopy wszystkich swoich nieprzyjaciół, którzy w nas są, i pokona w nas wszelką zwierzchność, władzę i moc.”\r\n\r\n \r\n\r\nProsimy Cię Panie o pokorę. Pomnóż wśród nas tęsknotę za Twoim Królestwem. Pomóż zobaczyć, że to, za czym tęsknimy jest na wyciągnięcie reki – jest tu i teraz. Prosimy Cię o pokorę, abyśmy potrafiły zostawić to, co się Tobie w naszym życiu nie podoba. Jezu, cichy i serca pokornego, oczyść nasze serca, aby nasz dom był Twoim duchowym rajem, gdzie Ty z upodobaniem mieszkasz. Uczyń nas pokornymi głosicielami Twojej Obecności i Królestwa, które jest pośród nas.",
        meditation2: "Jakże łatwo jest dzielić się Jezusem z tymi którzy słuchają, którzy chcą poznać Prawdę. Boże jak czasem trudno wybrać tylko 1 parę sandałów, jedną tylko podróżną torbę, by dać świadectwo tym którzy miłość znają tylko z filmów, Kościół z prasowych plotek. Łatwiej uśmiechać się do tych, którzy są mili, przebaczać tym, na których przebaczenie liczę. Jak wiele jest we mnie strachu jak mało zachwytu. Otwórz Panie moje oczy, serce i ręce niech sprawiam żeby rosło Twe Królestwo.\r\n\r\nJezu przynosimy Ci wszystkie rodziny, niech Twoje światło pomoże im na nowo odkrywać piękno i znaczenie kapłaństwa i życia konsekrowanego.",
        meditation3: "„Zachowaj nas od ognia piekielnego”\r\n\r\n\r\nJezu Ty nas każdego dnia nauczasz. Pragniesz naszego szczęścia. Nie chwilowej przyjemności, ale głębokiej radości, pokoju i wolności.\r\nNawrócić się. Zmienić myślenie. Czy pozwolę, abyś wszedł do mojego życia? Czy zgodzę się na to, że Ty wiesz lepiej? Nawet wtedy jeśli nie będzie to dla mnie proste. Czy jestem świadoma, że od mojej dzisiejszej decyzji będzie zależała moja przyszłość?"
    },
    {
        part: "swiatla",
        nr: "4",
        mystery: "Przemienienie na Górze Tabor",
        meditation1: "„Rozważ to wszystko i prowadź życie godne miłości – mówi św. Jan Chryzostom - Dlatego Pan najpierw przyszedł tutaj, abyś jeszcze przed przybyciem tam [do królestwa niebieskiego] poznał, że jesteś w stanie żyć na ziemi tak, jakbyś żył w niebie. Każdego dnia szukajmy Królestwa Niebieskiego, a wszystko co ziemskie uważajmy za cień i sen. Gdyby jakiś król wziął cię, będącego żebrakiem i potrzebującym, uczynił cię nagle swoim synem, nawet nie myślałbyś o swojej chacie i jej marności. Nigdy nie ceń tego, co ulotne, ponieważ do większych rzeczy zostałeś wezwany! Ten, który cię powołuje, jest Panem aniołów, a dawane ci dobra przekraczają rozum i wszelkie pojęcie.”\r\n\r\n \r\n\r\nProsimy Cię Panie o wiarę. Twoje szaty lśniły na górze, a uczniowie kontemplowali Twoją chwałę, by gdy zobaczą Cię na krzyżu, pojęli wielkość Twej miłości. Przymnóż nam wiary, abyśmy nie przeceniali w naszym życiu tego, co ulotne, ale w postawie uwielbienia czyniły wszystko na Twoją większą chwałę nawet w cierpieniu i ogołoceniu.",
        meditation2: "Jak łatwo ludzie dają się porwać nerwowym rytmom  czasów! Odkąd zgodzą się, że ważniejsze jest „ile” od  „jak” nie zaznają już spokoju. Wychyleni ku przyszłości lub zamknięci w tym, co było, nie zgodzą się na cierpliwe dojrzewanie, na smakowanie czasu. Ich szczęście nie nadąża za nimi, gdy tak biegną, pełni stresu i smutków. Boże ucz mnie cierpliwie kochać. Daj bym pokochał siłę ciszy, to co pokorne i nie dochodzi swego. Prowadź mnie wytrwale i cierpliwie aż do czasu kiedy na szczycie naszej góry, zapatrzony w Ciebie wyznam że spełniła się moja nadzieja.\r\n\r\nJezu niech Twoje światło mocno płonie we wszystkich ludziach powołanych – w Zgromadzeniach, seminariach i wspólnotach, niech się rozwijają zgodnie z Twoją wolą.",
        meditation3: "„Zaprowadź wszystkie dusze do nieba”\r\n\r\n\r\nStajemy przed Tobą Jezu, aby prosić o łaskę zbawienia dla dusz. Pragniemy być przy Tobie. Powtarzamy za uczniami: „Dobrze nam tu być.” Jak wiele w nas tęsknoty za dobrem, pięknem, czystą miłością. Nasze serca oczekują Ciebie, Twojej bliskości. Jeszcze raz chcemy prosić: „Zaprowadź nas do nieba.”"
    },
    {
        part: "swiatla",
        nr: "5",
        mystery: "Ustanowienie Eucharystii",
        meditation1: "„Człowiek, który miłuje Boga, nie potrzebuje przypomnienia, aby miłował bliźniego, a ten, kto miłuje bliźniego, co w nim miłuje, jeśli nie Boga? Pan dodał: „Jak ja was umiłowałem”. Co w nas bowiem On umiłował, jeśli nie Boga? - mówi św. Augustyn - Umiłował nie to, co mieliśmy, ale to, co będziemy mieć, aby nas doprowadzić tam, gdzie Bóg będzie wszystkim we wszystkich. Tak samo bowiem słusznie mówi się o lekarzu, że miłuje chorych: a co w nich miłuje, jeśli nie uzdrowienie, którego pragnie dokonać, a nie chorobę, którą przyszedł wyrzucić? Tak więc i my miłujmy siebie nawzajem, abyśmy, na tyle, na ile to możliwe, pociągali siebie nawzajem przez miłość i troskę do Boga, którego w sobie mamy.”\r\n\r\n\r\n\r\nProsimy Cię Panie o miłość. Jezu z Wieczernika, naucz nas jak Ty obmywać nogi naszym bliźnim, jak szczerze miłować w klęsce, stracie i bólu. Prosimy Cię Panie o miłość. Niech Eucharystia uczy nas jak adorować Ciebie i tracić życie dla bliźnich. Pomóż nam, Chryste Eucharystyczny, odkryć radość w miłości Boga i bliźniego.",
        meditation2: "Starsze kobiety, mężczyźni o spracowanych dłoniach, dzieci z błyszczącymi od łez policzkami, młodzi i starzy potrzebują lekarza, wołają o pomoc i zrozumienie. I choć potrafią wskrzeszać nadzieję z popiołów i ruin, to jak powietrza i chleba potrzebują znaku. Jezus przy nich stoi. Dłonie im kładzie za wzburzonych myślach. Boże mój strzeż mnie od łatwych rozwiązań trudnych spraw. Ja sam potrzebuję znaku i lekarstwa na moje niedowiarstwo. Zbaw we mnie człowieka, dotknij swoją dłonią moje powołanie, Niech Twe Ciało wykarmi mą lichą nadzieję bym zawsze dostrzegał Twoje światło, które nigdy nie gaśnie.\r\n\r\nJezu przynosimy Ci tegorocznych maturzystów, niech twoje światło dotknie ich serc i umysłów, by byli otwarci na każdą drogę którą im wskażesz.",
        meditation3: "„Szczególnie te, które najbardziej potrzebują Twojego miłosierdzia”\r\n\r\n\r\nJak mamy dążyć do Ciebie? Ty mówisz: „To jest Ciało Moje, które za was będzie wydane.” Ty jesteś moją siłą i to właśnie Ciebie potrzebuję aby żyć, aby kochać. Czy potrafię uznać prawdę, że to właśnie ja szczególnie potrzebuje Twojego miłosierdzia. To właśnie ja jestem tą osobą, która sama sobie nie poradzi. Czy umiem w pokorze wyznać, że: „Potrzebuję Ciebie!”"
    },
    {
        part: "bolesne",
        nr: "1",
        mystery: "Modlitwa Pana Jezusa w Ogrójcu",
        meditation1: "Modlitwa tak wytrwała, że aż przyniosła cierpienie. Cierpienie, które jest tylko dla tego kto kocha. Bo kochać to cierpieć. Ojcze, w odwiecznym planie umiłowania człowieka wiedziałeś już o cierpieniu Twego Syna a mimo to nie oszczędziłeś Go dla tej chwili.\r\n\r\nJezu, patrzę w Twoje oczy, w Twą twarz i widzę… widzę tylko miłość. Spojrzenie pełne miłości w cierpieniu… które jest dla mnie.",
        meditation2: "Jezus rozmawiając w ogrodzie oliwnym i zgadzając się na wolę Ojca nie wchodziłeś w pustkę, lecz oddawałeś się w pełni w ramiona Boga Ojca. To jedna z twych trudniejszych modlitw. Strach przed kielichem goryczy rozdzierał Ci serce. O współcierpiącej Maryi nikt nie powiedział, że po wypowiedzeniu swego „fiat” lęk opuścił Ciebie. Nikt nie napisał w ewangelii, że przestałaś się bać i odczuwać trwogę. To siła zawierzenia daję tę moc, by wypełniać wolę Boga.",
        meditation3: "„We wszystkim co czynisz, nie mniej innego pragnienia i zamiaru, jak podobać się Bogu (...)”\r\n\r\n\r\nModlitwa jest intymnym spotkaniem z Bogiem, w której serce z sercem się łączy. Jezus szukał miejsc pustynnych, osamotnienia, aby być z Ojcem. W najtrudniejszych chwilach, gdzie wydawałoby się, że nie ma żadnego wyjścia , rozwiązania, Jezus nieustannie trwał na modlitwie, trwał przy Ojcu. W Nim szukał pomocy.\r\nNasza modlitwa ma być naszym osobistym spotkaniem z Bogiem. Jezus powiedział: ”Wejdź do swojej izdebki zamknij drzwi i się módl”. Pokazuje nam, że nie jest najważniejsze, aby inni nas widzieli na modlitwie. Ale, aby w tym wszystkim odnaleźć Boga i Jemu się podobać. Z Nim trwać w pięknych, a także w tych trudniejszych chwilach. Trwać serce przy sercu."
    },
    {
        part: "bolesne",
        nr: "2",
        mystery: "Biczowanie Pana Jezusa",
        meditation1: "Cóż jeszcze Jezu przed tobą? Do czego będziesz jeszcze zdolny by mnie przekonać o Swojej Miłości? Ile jeszcze jej dowodów będę potrzebowała? A może to nauka dla mnie by kochać, tak cicho kochać cierpiąc.",
        meditation2: "Choć żaden bicz nie dotknął twych pleców, kotłujące myśli i słowa starca Symeona dręczyły twoje serce „Twoją duszę miecz przeniknie”. Jak to rozumieć? Co to oznacza?\r\nW życiu nie chodzi o to by nie odczuwać bólu, lecz Jezus czeka byśmy wszystkie troski przerzucały na Niego, bo Jemu zależy na nas.",
        meditation3: "„Wszystko z Boga – nic ze mnie”\r\n\r\n\r\nUderzenie, za uderzeniem Jezus przyjmuje na swoje ciało. Przyjmuje w milczeniu. W bólu Jezus ma wzrok skierowany do Ojca, który dodaje Mu sił. W codzienności przyjmujemy różne uderzenia na nasze ciało fizyczne, a także duchowe. W przyjmowaniu różnych uderzeń pomaga nam Ojciec który jest blisko nas.\r\nJezus pokazuje nam jak ważne jest, aby prosić Ojca o siłę w przyjmowaniu trudności. Bez  pomocy Ojca nie byłybyśmy wstanie przyjąć tego wszystkiego. Chce, abyśmy swój wzrok kierowali w górę do Ojca , abyśmy u Niego czerpali mocy i łaski. Bo tylko z Nim, pokonamy trudności, przyjmiemy każde uderzenie i będziemy mogli kroczyć dalej. Bo tylko serce złączone z Ojcem, odnajdzie prawdziwą bliskość."
    },
    {
        part: "bolesne",
        nr: "3",
        mystery: "Cierniem ukoronowanie",
        meditation1: "Król! Miłości w cierpieniu! Być oblubienicą takiego Króla. To znaczy zgodzić się, więcej, zobowiązać się by kochać miłością, która będzie odrzucona, podeptana, wyśmiana czy źle zrozumiana.  Bo kochać jak On to cierpieć.",
        meditation2: "Każdy cierń przeszył, także i Twoje niepokalane serce kochająca Matko. Dobrze wiesz co znaczy być niezrozumianym i nieprzyjętym. Mimo to nie zamykasz się w swym cierpieniu, lecz oczy twe zapatrzone są w królującą Miłość, która zwycięża wszystko.",
        meditation3: "„Wszystko Bogu – nic sobie”\r\n\r\n \r\n\r\nGdy ciało Jezusa zostało zranione biczowaniem, Jego twarz okryły krople krwi. Żołnierze uplótłszy  koronę z cierni, włożyli Mu ją na głowę, zadając kolejny ból. Jezus – milczał.  Życie niesie w sobie dużo niespodzianek, tych pięknych, a także trudnych. Trudno nam się zgodzić na te trudniejsze chwile, wolelibyśmy, aby ich nie było. Przejść przez życie łagodnie spokojnie, bez żadnych problemów.\r\nŻycie Jezusa pokazuje nam, że cierpienia, trudności mają sens. Bez nich znudziło by się nam życie i bylibyśmy ospali, nie widzielibyśmy głębszego sensu w życiu. Są one nam potrzebne, aby jeszcze bliżej spotkać się z Nim . Dostrzec jak cierpienia łączą. Gdy twarz Jezusa coraz mocniej opływała krwią, Jezus nie odrywał swojego spojrzenia od Ojca. Czerpał siły na dalszą wędrówkę. On to robił nie dla siebie, ale dla nas. Tylko oczy skierowane w stronę Ojca, dodadzą siły do dalszej wędrówki."
    },
    {
        part: "bolesne",
        nr: "4",
        mystery: "Droga krzyżowa",
        meditation1: "Miłość z Krzyżem na pierwszym planie. Miłość, która pragnie by ją unieruchomiono. Bo Ona wie, że wtedy będzie najskuteczniejsza, takiej Miłości nikt nie pokona",
        meditation2: "Choć fizycznie stałaś z boku, niosłaś krzyż razem z Nim. To spotkanie na drodze krzyżowej, to złączenie się dwóch kochających serc- dało ulgę w cierpieniu i pomogło donieść krzyż do końca.\r\nCierpienie dzielone na dwoje, zawsze wydaje się lżejsze. Prawdziwie współczująca Matko Jezusa, twa milcząca obecność najlepiej koi ból krwawiących ran i pomaga iść wciąż na przód.",
        meditation3: "„Wszystko dla Boga – nic dla siebie”\r\n\r\n\r\nDroga nie była łatwa, sił coraz mniej, a każdy upadek powodował coraz więcej raz na ciele Jezusa. Gdy upadał, pod ciężarem, to się nie poddawał, podnosił się i szedł dalej bo wiedział dla kogo.\r\nNasze życie, codzienność jest też drogą, wędrówką, która prowadzi po pagórkach, krętych drogach, a także po prostych ścieżkach. W kroczeniu drogą zawsze towarzyszy nam jakiś cel, który dodaje nam sił. Jezus gdy kroczył swoją drogą krzyżową, wiedział dlaczego i dla kogo to robił. Miłość do nas doprowadziła Go na sam szczyt.\r\nJezus uczy nas swoim życiem jak ważny jest cel naszej drogi, dla kogo to robimy. Abyśmy idąc tą drogą, potrafili oddawać to wszystko Ojcu, dążyć do spotkania z Nim, ale nie pomijając tego wszystkiego co nam przygotował. Droga samemu przez życie nie jest łatwa, ale droga z Nim jest piękna pomimo trudności. Idąc nie gromadź skarbów dla siebie, bo zmierzając do celu – odnajdziesz najcenniejszy skarb – Boga."
    },
    {
        part: "bolesne",
        nr: "5",
        mystery: "Śmierć na krzyżu",
        meditation1: "Wydaje się, że tu nastąpił kres życia. Nie dla człowieka wiary i miłości. Tak bardzo trzeba być uważnym, by dostrzec jak z umierającego ziarna wybija się  zielone źdźbło życia. Jak bardzo trzeba kochać, by uwierzyć, że miłość jest warta nawet utraty życia.",
        meditation2: "Stałaś pod krzyżem do głębi przeniknięta Jego śmiercią. Twoja wiara zrodziła nadzieję, że śmierć to jeszcze nie koniec. Ostatnie słowo należy do Miłości. Przez całe życie wiedziałaś co to znaczy umierać. Patrzyłaś jak krzyżują twego Syna, współcierpiąc z Nim, jednocześnie umierało twoje serce.\r\nProszę Cię Maryjo, abyś była w godzinie mojej śmierci i pomogła mi przejść na drugą stronę życia.",
        meditation3: "„Nic tak mnie nie jednoczy z Najświętszym Sercem naszego Pana Jezusa Chrystusa jak krzyż, który jest najcenniejszym zadatkiem Jego Miłości”.\r\n\r\nDroga ukończona, miłość dodawała Jezusowi sił, aby zrobić ostatnie kroki aby dotrzeć na szczyt. Wydawałoby się, że to koniec, a to dopiero początek. Bywają w życiu chwile, gdy mówimy , że to koniec, nie mam więcej sił, aby walczyć. Że już nic więcej nie da się zrobić. A Jezus pokazuje, że da się. Daje nam przykład miłości – miłości Ojca która nas prowadzi , która niesie nas na swych ramionach.\r\nGdy myślimy o krzyżu, to budzi w nas  trwogę w sercu, lęk, uciekamy od Niego. Jezus mówi do nas nie bój się, zaufaj, daj się poprowadzić. Spójrz do czego jest zdolna prawdziwa miłość, pokonać wszystkie trudności. Dla miłości nie ma nic nie możliwego.\r\nTylko krzyż może nas w pełni zjednoczyć z Chrystusem. Więc nie lękaj się, On jest gotów Ci pomóc, biorąc swój krzyż z miłości, idzie razem z Tobą twoją drogą. Droga Chrystusa – to droga miłości przez krzyż."
    }
]

}
